package smartuniversityacademicsystem.scheduling;

import java.sql.*;
import java.util.*;
import java.util.stream.Collectors;
import smartuniversityacademicsystem.db.TimetableDAO;
import smartuniversityacademicsystem.model.*;

/**
 * Greedy timetable scheduler with three-layer conflict detection:
 *   1. Lecturer conflict  – same lecturer teaching two courses simultaneously
 *   2. Room conflict      – same room used by two courses simultaneously
 *   3. Student conflict   – a student enrolled in two courses at the same time
 *
 * Room selection uses best-fit: smallest room that still fits the enrolled count.
 * Courses are processed largest-enrolment-first so popular courses get prime slots.
 */
public class TimetableGenerator {

    private static final int SESSIONS_PER_WEEK = 2;

    private static final String[] DAYS = {
        "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
    };

    private static final String[][] SLOTS = {
        {"08:00", "10:00"},
        {"10:00", "12:00"},
        {"14:00", "16:00"},
        {"16:00", "18:00"}
    };

    // ── Result container ──────────────────────────────────────────────────────

    public static class GenerationResult {
        public final int         scheduled;
        public final List<String> conflicts;
        public final List<String> log;

        GenerationResult(int scheduled, List<String> conflicts, List<String> log) {
            this.scheduled = scheduled;
            this.conflicts = conflicts;
            this.log       = log;
        }
    }

    private final TimetableDAO dao;

    public TimetableGenerator(TimetableDAO dao) {
        this.dao = dao;
    }

    // ── Main entry point ──────────────────────────────────────────────────────

    public GenerationResult generate(int semesterId) throws SQLException {
        List<Course> courses = dao.getCoursesForScheduling();
        List<Room>   rooms   = dao.getRooms();

        if (rooms.isEmpty()) {
            return new GenerationResult(0,
                Collections.singletonList("No rooms defined. Add rooms before generating."),
                Collections.emptyList());
        }

        // Clear previously auto-generated entries for this semester
        dao.clearAutoGenerated(semesterId);

        // In-memory booking maps — O(1) conflict lookups
        // key = "day_HH:mm"
        Map<String, Set<Integer>> roomBookings     = new HashMap<>();
        Map<String, Set<Integer>> lecturerBookings = new HashMap<>();
        Map<String, Set<Integer>> studentBookings  = new HashMap<>(); // key -> Set<studentId>

        // Pre-load manually entered entries so we respect them during generation
        preloadManualEntries(semesterId, roomBookings, lecturerBookings, studentBookings);

        // Pre-load enrolled students per course to avoid repeated DB calls in the loop
        Map<Integer, List<Integer>> courseStudents = new HashMap<>();
        for (Course c : courses) {
            courseStudents.put(c.getId(), dao.getEnrolledStudents(c.getId()));
        }

        // Best-fit room list: sorted smallest-capacity first
        List<Room> sortedRooms = rooms.stream()
            .sorted(Comparator.comparingInt(Room::getCapacity))
            .collect(Collectors.toList());

        List<String> conflicts = new ArrayList<>();
        List<String> log       = new ArrayList<>();

        for (Course course : courses) {
            int      sessionsAssigned = 0;
            Set<String> usedDays     = new HashSet<>();

            outerLoop:
            for (String day : DAYS) {
                if (usedDays.contains(day)) continue;

                for (String[] slot : SLOTS) {
                    String slotKey = day + "_" + slot[0];

                    // ── 1. Lecturer conflict ──────────────────────────────────
                    if (course.getLecturerId() != 0) {
                        Set<Integer> lb = lecturerBookings.getOrDefault(slotKey, Collections.emptySet());
                        if (lb.contains(course.getLecturerId())) continue;
                    }

                    // ── 2. Student conflict ───────────────────────────────────
                    List<Integer> enrolled = courseStudents.getOrDefault(course.getId(), Collections.emptyList());
                    Set<Integer>  sb       = studentBookings.getOrDefault(slotKey, Collections.emptySet());
                    boolean studentConflict = enrolled.stream().anyMatch(sb::contains);
                    if (studentConflict) continue;

                    // ── 3. Room selection (best-fit + room conflict) ──────────
                    Room chosen = selectRoom(sortedRooms, course.getEnrolledCount(), slotKey, roomBookings);
                    if (chosen == null) continue; // all rooms occupied

                    // ── All checks passed — assign the slot ───────────────────
                    dao.saveGeneratedEntry(course.getId(), day, slot[0], slot[1],
                                           chosen.getId(), semesterId);

                    // Update in-memory maps
                    roomBookings.computeIfAbsent(slotKey,     k -> new HashSet<>()).add(chosen.getId());
                    if (course.getLecturerId() != 0)
                        lecturerBookings.computeIfAbsent(slotKey, k -> new HashSet<>()).add(course.getLecturerId());
                    enrolled.forEach(sid ->
                        studentBookings.computeIfAbsent(slotKey, k -> new HashSet<>()).add(sid));

                    usedDays.add(day);
                    sessionsAssigned++;
                    log.add(String.format("%-12s %-10s %-12s %s-%s  Lecturer: %s  Students: %d",
                        day, course.getCode(), chosen.getName(),
                        slot[0], slot[1], course.getLecturerName(), enrolled.size()));

                    if (sessionsAssigned == SESSIONS_PER_WEEK) break outerLoop;
                    break; // different day for next session
                }
            }

            if (sessionsAssigned < SESSIONS_PER_WEEK) {
                String reason = diagnoseFailure(course, sessionsAssigned);
                conflicts.add(course.getCode() + ": " + reason);
            }
        }

        return new GenerationResult(courses.size() - conflicts.size(), conflicts, log);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Best-fit room selection:
     * Returns the smallest room with enough capacity that is not already booked.
     * Falls back to the largest available room if none fit.
     */
    private Room selectRoom(List<Room> sortedRooms, int needed,
                            String slotKey, Map<String, Set<Integer>> roomBookings) {
        Set<Integer> booked = roomBookings.getOrDefault(slotKey, Collections.emptySet());

        // Best-fit: smallest room that fits
        for (Room r : sortedRooms) {
            if (!booked.contains(r.getId()) && r.getCapacity() >= needed)
                return r;
        }

        // Fallback: largest available room even if capacity is insufficient
        List<Room> reversed = new ArrayList<>(sortedRooms);
        Collections.reverse(reversed);
        for (Room r : reversed) {
            if (!booked.contains(r.getId()))
                return r;
        }

        return null; // all rooms occupied at this slot
    }

    /**
     * Pre-load manually entered timetable entries into in-memory booking maps
     * so the generator respects them as constraints.
     */
    private void preloadManualEntries(int semesterId,
                                      Map<String, Set<Integer>> roomBookings,
                                      Map<String, Set<Integer>> lecturerBookings,
                                      Map<String, Set<Integer>> studentBookings)
            throws SQLException {
        String sql =
            "SELECT t.day_of_week, TIME_FORMAT(t.start_time,'%H:%i') AS st, " +
            "       t.room_id, COALESCE(c.lecturer_id,0) AS lec_id, c.id AS course_id " +
            "FROM timetable t JOIN courses c ON t.course_id = c.id " +
            "WHERE t.semester_id = ? AND t.auto_generated = FALSE";

        try (PreparedStatement ps = smartuniversityacademicsystem.db.DatabaseConnection
                .getConnection().prepareStatement(sql)) {
            ps.setInt(1, semesterId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    String key    = rs.getString("day_of_week") + "_" + rs.getString("st");
                    int    roomId = rs.getInt("room_id");
                    int    lecId  = rs.getInt("lec_id");
                    int    cId    = rs.getInt("course_id");

                    if (roomId > 0) roomBookings.computeIfAbsent(key, k -> new HashSet<>()).add(roomId);
                    if (lecId  > 0) lecturerBookings.computeIfAbsent(key, k -> new HashSet<>()).add(lecId);

                    // Load students for this manually scheduled course
                    dao.getEnrolledStudents(cId).forEach(sid ->
                        studentBookings.computeIfAbsent(key, k -> new HashSet<>()).add(sid));
                }
            }
        }
    }

    private String diagnoseFailure(Course course, int assigned) {
        if (assigned == 0) return "No suitable slot found — possible lecturer, room and student conflicts on all days.";
        return "Only " + assigned + "/" + SESSIONS_PER_WEEK + " sessions could be scheduled.";
    }
}
