package smartuniversityacademicsystem.scheduling;

import java.sql.SQLException;
import java.util.*;
import smartuniversityacademicsystem.db.TimetableDAO;
import smartuniversityacademicsystem.model.*;

/**
 * Greedy timetable scheduler.
 *
 * Strategy:
 *  1. Sort courses by enrolment descending (largest classes get priority).
 *  2. For each course assign SESSIONS_PER_WEEK slots across different days.
 *  3. For each candidate (day, slot, room) check:
 *       - lecturer not already teaching at that time
 *       - room not already occupied at that time
 *  4. Record unresolvable courses as conflicts.
 */
public class TimetableGenerator {

    // Two 2-hour sessions per week per course
    private static final int SESSIONS_PER_WEEK = 2;

    private static final String[] DAYS = {
        "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
    };

    // Lunch (12:00-14:00) is excluded
    private static final String[][] SLOTS = {
        {"08:00", "10:00"},
        {"10:00", "12:00"},
        {"14:00", "16:00"},
        {"16:00", "18:00"}
    };

    public static class GenerationResult {
        public final int            scheduled;
        public final List<String>   conflicts;     // course codes that couldn't be placed
        public final List<String>   log;           // human-readable schedule log

        GenerationResult(int scheduled, List<String> conflicts, List<String> log) {
            this.scheduled = scheduled;
            this.conflicts = conflicts;
            this.log       = log;
        }
    }

    private final TimetableDAO dao;

    public TimetableGenerator(TimetableDAO dao) {
        this.dao = dao;
    }

    public GenerationResult generate(int semesterId) throws SQLException {
        List<Course> courses = dao.getCoursesForScheduling();
        List<Room>   rooms   = dao.getRooms();

        if (rooms.isEmpty()) {
            return new GenerationResult(0,
                Collections.singletonList("No rooms defined in the database."),
                Collections.emptyList()
            );
        }

        // Clear previously auto-generated entries for this semester
        dao.clearAutoGenerated(semesterId);

        // In-memory conflict maps for O(1) lookups during generation
        // key = "day_HH:mm", value = set of room ids or lecturer ids already booked
        Map<String, Set<Integer>> roomBookings     = new HashMap<>();
        Map<String, Set<Integer>> lecturerBookings = new HashMap<>();

        // Pre-load manually entered entries into the in-memory maps
        preloadExistingConflicts(semesterId, roomBookings, lecturerBookings);

        List<String> conflicts = new ArrayList<>();
        List<String> log       = new ArrayList<>();

        for (Course course : courses) {
            int sessionsAssigned = 0;
            Set<String> usedDays = new HashSet<>();

            outerLoop:
            for (String day : DAYS) {
                if (usedDays.contains(day)) continue;

                for (String[] slot : SLOTS) {
                    String slotKey = day + "_" + slot[0];

                    // Lecturer conflict check (in-memory)
                    if (course.getLecturerId() != 0) {
                        Set<Integer> lecBooked = lecturerBookings.getOrDefault(slotKey, Collections.emptySet());
                        if (lecBooked.contains(course.getLecturerId())) continue;
                    }

                    // Find a free room
                    for (Room room : rooms) {
                        Set<Integer> roomBooked = roomBookings.getOrDefault(slotKey, Collections.emptySet());
                        if (roomBooked.contains(room.getId())) continue;

                        // Slot is free — assign it
                        dao.saveGeneratedEntry(
                            course.getId(), day, slot[0], slot[1], room.getId(), semesterId
                        );

                        // Update in-memory maps
                        roomBookings.computeIfAbsent(slotKey, k -> new HashSet<>()).add(room.getId());
                        if (course.getLecturerId() != 0) {
                            lecturerBookings.computeIfAbsent(slotKey, k -> new HashSet<>()).add(course.getLecturerId());
                        }

                        usedDays.add(day);
                        sessionsAssigned++;
                        log.add(String.format("  %s  %-10s  %s  %s-%s  %s",
                            day, course.getCode(), room.getName(), slot[0], slot[1],
                            course.getLecturerName()));

                        if (sessionsAssigned == SESSIONS_PER_WEEK) break outerLoop;
                        break; // move to next day for second session
                    }
                }
            }

            if (sessionsAssigned < SESSIONS_PER_WEEK) {
                conflicts.add(course.getCode() + " – only " + sessionsAssigned
                    + "/" + SESSIONS_PER_WEEK + " sessions could be scheduled.");
            }
        }

        return new GenerationResult(courses.size() - conflicts.size(), conflicts, log);
    }

    // Load manually entered timetable entries into in-memory booking maps
    private void preloadExistingConflicts(int semesterId,
                                          Map<String, Set<Integer>> roomBookings,
                                          Map<String, Set<Integer>> lecturerBookings)
            throws SQLException {
        String sql =
            "SELECT t.day_of_week, TIME_FORMAT(t.start_time,'%H:%i') AS st, " +
            "t.room_id, COALESCE(c.lecturer_id,0) AS lec_id " +
            "FROM timetable t JOIN courses c ON t.course_id = c.id " +
            "WHERE t.semester_id = ? AND t.auto_generated = FALSE";
        try (var ps = smartuniversityacademicsystem.db.DatabaseConnection
                .getConnection().prepareStatement(sql)) {
            ps.setInt(1, semesterId);
            try (var rs = ps.executeQuery()) {
                while (rs.next()) {
                    String key = rs.getString("day_of_week") + "_" + rs.getString("st");
                    int roomId = rs.getInt("room_id");
                    int lecId  = rs.getInt("lec_id");
                    if (roomId > 0) roomBookings.computeIfAbsent(key, k -> new HashSet<>()).add(roomId);
                    if (lecId  > 0) lecturerBookings.computeIfAbsent(key, k -> new HashSet<>()).add(lecId);
                }
            }
        }
    }
}
